### ISSUE TITLE
model is not getting trained

### ISSUE THREAD

**Issue by VempatiSaipriya** [MidhaTahir/Smart_NEDIANS#6]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Anaconda\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "<ipython-input-2-285fee2f5ae4>", line 14, in marking
    recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: module 'cv2.cv2' has no attribute 'face'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Anaconda\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "<ipython-input-2-285fee2f5ae4>", line 14, in marking
    recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: module 'cv2.cv2' has no attribute 'face'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Anaconda\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "<ipython-input-2-285fee2f5ae4>", line 14, in marking
    recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: module 'cv2.cv2' has no attribute 'face'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Anaconda\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "<ipython-input-2-285fee2f5ae4>", line 14, in marking
    recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: module 'cv2.cv2' has no attribute 'face'
​

**Comment by MidhaTahir** [comment]
Maybe this [Link](https://stackoverflow.com/questions/44633378/attributeerror-module-cv2-cv2-has-no-attribute-createlbphfacerecognizer) will resolve the issue you are getting.
